# Generated by Django 3.2.5 on 2022-01-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
