# Generated by Django 3.2.5 on 2022-01-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_auto_20220123_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='event_date',
        ),
    ]
