# Generated by Django 3.2.5 on 2022-01-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_booking_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
