# Generated by Django 3.2.5 on 2022-01-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_booking_rejected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['event_date']},
        ),
    ]
