# Generated by Django 3.2.5 on 2022-01-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_alter_booking_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
