# Generated by Django 3.2.5 on 2022-01-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_alter_booking_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_date',
            field=models.DateField(blank=True, error_messages={'unique': 'The Geeks Field you entered is not unique.'}, null=True, unique=True),
        ),
    ]
