# Generated by Django 3.2.5 on 2022-01-30 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_alter_booking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['sent_date']},
        ),
    ]
