# Generated by Django 3.2.5 on 2022-01-31 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_alter_booking_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='last_name',
        ),
    ]
