# Generated by Django 3.2.5 on 2022-01-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_alter_booking_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_date',
            field=models.DateField(blank=True, error_messages={'unique': 'Studio is already booked on that date. Please select a different date.'}, null=True, unique=True),
        ),
    ]
