# Generated by Django 3.2.5 on 2022-01-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_alter_booking_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='last_name',
            field=models.CharField(error_messages={'unique': 'Studio is already booked on that date. Please select a different date.'}, max_length=50, unique=True),
        ),
    ]
