# Generated by Django 3.2.5 on 2022-01-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_alter_booking_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
