# Generated by Django 3.2.5 on 2022-01-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_alter_booking_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='request',
            field=models.CharField(max_length=50),
        ),
    ]
