# Generated by Django 3.2.5 on 2022-01-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_alter_booking_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_time',
            field=models.TimeField(null=True),
        ),
    ]
