# Generated by Django 3.2.5 on 2022-11-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wkc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wkcbooking',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='wkcbooking',
            name='accepted_date',
        ),
        migrations.RemoveField(
            model_name='wkcbooking',
            name='rejected',
        ),
    ]
